# Site settings
name: Subhradeep Biswas
email: subhradeepbiswas.asuse@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, Python, Java, SQL, PL/SQL, Relational Database Design, Object-Oriented Design, Agile (Scrum) Project Management"
moserscomment: "I relied heavily on Subhradeep’s knowledge and prior experience to make decisions on the correctness of alternative solutions to assignments and exercises. "
moserssign: "- Dr. Kathleen Moser, PhD, Professor, Arizona State University"
skills: "Senior Software Engineer in Pleasanton, CA"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/subhradeep-biswas-asu/
  #- title: medium
  #  url: https://medium.com/@cgroom
  #- title: twitter
  #  url: https://twitter.com/chuck_groom
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
